daemons:
  - name: nnf-fence
    repository: nnf-sos
    serviceAccount:
      name: nnf-fencing-agent
      namespace: nnf-system
  - name: nnf-data-movement
    bin: nnf-dm
    buildCmd: make build-daemon
    path: bin/
    repository: nnf-dm
    serviceAccount:
      name: nnf-dm-daemon
      namespace: nnf-dm-system
    extraArgs: '--kubernetes-qps 50 --kubernetes-burst 100'
  - name: client-mount
    bin: clientmountd
    buildCmd: make build-daemon
    path: bin/
    repository: dws
    skipNnfNodeName: true
    serviceAccount:
      name: dws-clientmount
      namespace: dws-system
