libraries:
  - name: nnf-dm-usercontainer
    lib:
      name: libcopyoffload.a
      dest: /opt/local/lib/
    path: daemons/lib-copy-offload/
    buildCmd: make -C daemons/lib-copy-offload libcopyoffload.a
    repository: nnf-dm
    secret:
      name: nnf-dm-usercontainer-client-tls
      namespace: default
