libraries:
  - name: copy-offload
    lib:
      name: libcopyoffload.a
      dest: /opt/local/lib/
    path: daemons/lib-copy-offload/
    buildCmd: make -C daemons/lib-copy-offload libcopyoffload.a
    repository: nnf-dm
    secret:
      name: nnf-dm-copy-offload-client-tls
      namespace: default
