repositories:
  # Remote References:
  #   If useRemoteK==true, then use the remote reference to the kustomize
  #   configuration rather than referring to the local workarea.
  #   Examples for the build value:
  #     v0.0.3 (a tag)
  #     master (most recent build from the master branch)
  #     a branch name (whether it is or isn't a PR)
  #   The url may contain up to two %s format specifiers.  If the repo
  #   contains overlays, then the first %s indicates where the overlay name
  #   will be inserted.  The final %s indicates where the build value will be
  #   inserted.
  #   Example:
  #     useRemote: true
  #     remoteReference:
  #       build: v0.0.3
  #       url: https://github.com/HewlettPackard/lustre-csi-driver.git/deploy/kubernetes/%s/?ref=%s
  #
  - name: dws
    overlays: [craystack, kind, dp0]
    development: https://ghcr.io/hewlettpackard/dws
    master: https://ghcr.io/hewlettpackard/dws
  - name: nnf-dm
    development: https://ghcr.io/nearnodeflash/nnf-dm
    master: https://ghcr.io/nearnodeflash/nnf-dm
  - name: nnf-sos
    overlays: [craystack, kind, dp0]
    development: https://ghcr.io/nearnodeflash/nnf-sos
    master: https://ghcr.io/nearnodeflash/nnf-sos
    env:
    # The nnf-mfu container to use in NNFContainerProfile resources.
    # Example values:
    #  - A specific release build: 0.0.1 (without the "v" prefix)
    #  - The most recent build from the master branch: master
    - name: NNFMFU_VERSION
      value: 0.0.1
  - name: lustre-csi-driver
    overlays: [overlays/rabbit, overlays/kind]
    development: https://ghcr.io/hewlettpackard/lustre-csi-driver
    master: https://ghcr.io/hewlettpackard/lustre-csi-driver
    useRemoteK: true
    remoteReference:
      build: v0.0.4
      url: https://github.com/HewlettPackard/lustre-csi-driver.git/deploy/kubernetes/%s/?ref=%s
  - name: lustre-fs-operator
    development: https://ghcr.io/nearnodeflash/lustre-fs-operator
    master: https://ghcr.io/nearnodeflash/lustre-fs-operator
    useRemoteK: true
    remoteReference:
      build: v0.0.3
      url: https://github.com/NearNodeFlash/lustre-fs-operator.git/config/default/?ref=%s
