repositories:
  - name: hpc-dpm-dws-operator
    overlays: [craystack, kind]
    development: https://arti.dev.cray.com/artifactory/kj-docker-unstable-local/cray-dws-operator/
    master: https://arti.dev.cray.com/artifactory/kj-docker-master-local/cray-dws-operator/
  - name: hpc-rabsw-lustre-fs-operator
    development: https://arti.dev.cray.com/artifactory/rabsw-docker-unstable-local/cray-dp-lustre-fs-operator/
    master: https://arti.dev.cray.com/artifactory/rabsw-docker-master-local/cray-dp-lustre-fs-operator/
  - name: hpc-rabsw-lustre-csi-driver
    overlays: [lustre]
    development: https://arti.dev.cray.com/artifactory/rabsw-docker-unstable-local/cray-dp-lustre-csi-driver/
    master: https://arti.dev.cray.com/artifactory/rabsw-docker-master-local/cray-dp-lustre-csi-driver/
  - name: hpc-rabsw-nnf-dm
    development: https://arti.dev.cray.com/artifactory/rabsw-docker-unstable-local/cray-dp-nnf-dm/
    master: https://arti.dev.cray.com/artifactory/rabsw-docker-master-local/cray-dp-nnf-dm/
  - name: hpc-rabsw-nnf-sos
    overlays: [craystack, kind, dp0]
    development: https://arti.dev.cray.com/artifactory/rabsw-docker-unstable-local/cray-dp-nnf-sos/
    master: https://arti.dev.cray.com/artifactory/rabsw-docker-master-local/cray-dp-nnf-sos/