
systems:
- name: rabbit-dev
  aliases: [dp0, rabbit-dev-01, rabbit-lab]
  master: rabbit-dev-cn-04
  workers: [rabbit-dev-cn-03]
  rabbits:
    rabbit-dev-01: [rabbit-dev-cn-01, rabbit-dev-cn-02]
- name: rabbit-htx
  aliases: [dp1]
  master: rabbit-k8s-master
  workers: [rabbit-k8s-worker]
  rabbits:
    rabbit-node-0:
    rabbit-node-1: [compute-node-0, compute-node-1]