systems:
  - name: kind
    aliases: [kind-kind]
    overlays: [kind, overlays/kind]
    workers: [kind-worker]
    ports: ["5000-5999"]
    rabbits:
      kind-worker2: { 0: compute-01, 1: compute-02, 6: compute-03 }
      kind-worker3: { 4: compute-04 }
  - name: craystack-default
    aliases: [craystack]
    overlays: [craystack]
    workers: [k3s-master]
    ports: ["5000-5999"]
    rabbits:
      rabbit-01: { 0: compute-01 }
      rabbit-02:
      rabbit-03:
  - name: rabbit-dev
    aliases: [dp0, rabbit-dev-01, rabbit-lab]
    overlays: [dp0, overlays/rabbit]
    workers: [rabbit-dev-cn-02]
    ports: ["5000-5999"]
    rabbits:
      rabbit-dev-01:
        {
          0: rabbit-dev-cn-01,
          1: rabbit-dev-cn-02,
          2: rabbit-dev-cn-03,
          3: rabbit-dev-cn-04,
        }
  - name: rabbit-htx
    aliases: [dp1, dp1a, htx-1]
    overlays: [dp0, overlays/rabbit]
    workers: [rabbit-k8s-worker]
    ports: ["5000-5999"]
    rabbits:
      rabbit-node-1: { 0: compute-node-3, 1: compute-node-2 } # These computes are physically swapped
      rabbit-node-2: { 0: compute-node-4, 1: compute-node-5 }
