# Describes Rabbit "htx-1", or "dp0", and its compute nodes.
apiVersion: dataworkflowservices.github.io/v1alpha3
kind: SystemConfiguration
metadata:
  # Nnf-sos expects this resource to be default/default.
  name: default
  namespace: default
spec:
  ports:
  - 5000-5999
  portsCooldownInSeconds: 0
  storageNodes:
  - computesAccess:
    - index: 0
      name: rabbit-compute-3
    - index: 1
      name: rabbit-compute-2
    name: rabbit-node-1
    type: Rabbit
  - computesAccess:
    - index: 0
      name: rabbit-compute-4
    - index: 1
      name: rabbit-compute-5
    name: rabbit-node-2
    type: Rabbit
