# Describes the Rabbit nodes created for the KIND environment, and some
# imaginary compute nodes for those rabbits.
apiVersion: dataworkflowservices.github.io/v1alpha3
kind: SystemConfiguration
metadata:
  # Nnf-sos expects this resource to be default/default.
  name: default
  namespace: default
spec:
  ports:
  - 5000-5999
  portsCooldownInSeconds: 0
  storageNodes:
  - computesAccess:
    - index: 0
      name: compute-01
    - index: 1
      name: compute-02
    - index: 6
      name: compute-03
    name: kind-worker2
    type: Rabbit
  - computesAccess:
    - index: 4
      name: compute-04
    name: kind-worker3
    type: Rabbit
