systems:
  - name: kind
    aliases: [kind-kind]
    overlays: [kind, overlays/kind]
    systemConfiguration: systemconfiguration-kind.yaml
  - name: rabbit-htx
    aliases: [dp1, dp1a, htx-1]
    overlays: [dp0, examples-htx, overlays/rabbit]
    systemConfiguration: systemconfiguration-htx-1.yaml
  - name: rabbit-tds
    aliases: [htx-tds]
    overlays: [dp0, overlays/rabbit]
    systemConfiguration: systemconfiguration-htx-tds.yaml
    k8sHost: 10.168.0.33
