
systems:
- name: kind
  aliases: [kind-kind]
  overlays: [kind]
  master: kind-control-plane
  workers:
  rabbits:
    kind-worker:
    kind-worker2:
- name: rabbit-dev
  aliases: [dp0, rabbit-dev-01, rabbit-lab]
  overlays: [dp0,lustre]
  master: rabbit-dev-cn-04
  workers: [rabbit-dev-cn-03]
  rabbits:
    rabbit-dev-01: [rabbit-dev-cn-01, rabbit-dev-cn-02]
- name: rabbit-htx
  aliases: [dp1, dp1a]
  overlays: [dp0,lustre]
  master: rabbit-k8s-master
  workers: [rabbit-k8s-worker]
  rabbits:
    rabbit-node-0:
    rabbit-node-1: [compute-node-0, compute-node-1]
- name: rabbit-htx-2
  aliases: [htx-2]
  overlays: [dp0,lustre]
  master: rabbit-compute-4
  workers: [rabbit-compute-5]
  rabbits:
    rabbit-node-2: [rabbit-compute-4, rabbit-compute-5]
