# An override for the argocd helm chart.
#
# helm repo add argo https://argoproj.github.io/argo-helm
# helm repo update argo
# helm search repo argocd
# helm show values argo/argo-cd --version $CHART_VER > argocd.yaml
#
# helm install argocd -n argocd --create-namespace argo/argo-cd \
#   --version $CHART_VER -f $THIS_OVERRIDE_FILE

---
global:
  image:
    tag: "v2.6.6"

server:
  extraArgs:
    # Prevent argocd from generating self-cert and redirect http to https.
    - --insecure
    # "Instead, should use ingress and terminate https on the ingress level,
    # then route plain http to argocd."

configs:
  cm:
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs

