name: NNF Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Go version
      run: go version
    - name: Get Ginkgo
      run: GOPATH="/root/go" go get github.com/onsi/ginkgo/v2/ginkgo@v2.8.1
    - name: Get Gomega
      run: GOPATH="/root/go" go get github.com/onsi/gomega/...
    - name: Install Ginkgo
      run: GOCACHE="/root/.cache/go-build" GOPATH="/root/go" go install github.com/onsi/ginkgo/v2/ginkgo
    - run: ginkgo run -p --vv ./test/...
