name: NNF Test

on:
  push:

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      submodules: 'true'
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Setup Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo && go get github.com/onsi/gomega/...
    - name: Test
      run: ginkgo run -p --vv ./test/...
