name: NNF Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Setup Ginkgo
      run: >
        GINKGO_MOD=$(grep "github.com/onsi/ginkgo" go.mod | awk '{print $1 "@" $2}')
        GINKGO_PATH=$(grep "github.com/onsi/ginkgo" go.mod | awk '{print $1}')
        echo "Using $GINKGO_MOD" &&
        go get $GINKGO_MOD && go install $GINKGO_PATH && go get github.com/onsi/gomega/...
    - run: ginkgo run -p --vv ./test/...
